### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by mrmaly** [Michal256/Bubble_Invasion#1]
I believe it would be a good idea to somehow attract the user's attention to the words / expressions they don't know. I don't want to suggest a specific solution because there are many, but I guess something needs to be done in order to make this app teach people and not just make them just at randomly displayed bubbles.
But I'm really happy for you. I know you are making a progress in something that you derive a great deal of enjoyment from. And this is the most important thing.

**Comment by Michal256** [comment]
Thank you very much for your opinion and suggestion. I must admit that application which I created, could be better. If there will be an opportunity, to create similar applciation, I will try to solve such issues. There is still much work to be done, but I hope, that in time, my applications, will become way better, specially in performance.
